apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 192.168.97.84/32
    cni.projectcalico.org/podIPs: 192.168.97.84/32
  creationTimestamp: "2021-03-25T08:07:46Z"
  labels:
    x: murali36webpod1
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:x: {}
      f:spec:
        f:containers:
          k:{"name":"murali36webpod1"}:
            .: {}
            f:env:
              .: {}
              k:{"name":"x"}:
                .: {}
                f:name: {}
                f:value: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":80,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:protocol: {}
            f:resources: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
    manager: kubectl-replace
    operation: Update
    time: "2021-03-25T08:07:46Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:cni.projectcalico.org/podIP: {}
          f:cni.projectcalico.org/podIPs: {}
    manager: calico
    operation: Update
    time: "2021-03-25T08:07:47Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"192.168.97.84"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2021-03-25T08:07:48Z"
  name: murali36webpod1
  namespace: default
  resourceVersion: "33880"
  uid: 76dd7eee-0519-4e69-8510-94cafe43ae42
spec:
  containers:
  - env:
    - name: x
      value: website1
    image: 125690/ciscoweb1:march2021v1
    imagePullPolicy: IfNotPresent
    name: murali36webpod1
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-56cvf
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minion-node-2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-56cvf
    secret:
      defaultMode: 420
      secretName: default-token-56cvf
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-03-25T08:07:46Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-03-25T08:07:48Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-03-25T08:07:48Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-03-25T08:07:46Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://ca8e193358c911ee0a04f24dbf9fb00c74feea8628d5b55f4085c2dcc3a76130
    image: 125690/ciscoweb1:march2021v1
    imageID: docker-pullable://125690/ciscoweb1@sha256:abef5da6d15691e8e541fb6d68afdd8b7a835568d40710eb4ab0856d08de9402
    lastState: {}
    name: murali36webpod1
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-03-25T08:07:47Z"
  hostIP: 172.31.64.94
  phase: Running
  podIP: 192.168.97.84
  podIPs:
  - ip: 192.168.97.84
  qosClass: BestEffort
  startTime: "2021-03-25T08:07:46Z"
