apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels: # this is for label creation of POD 
    x: helloashu # x is key and helloashu is a value 
  name: ashuwebpod # name of POD 
spec:
  containers:
  - image: dockerashu/ciscoweb:march2021v1 # docker image from Docker hub 
    name: ashuwebpod # name of container 
    env: # create/replace env variable and values 
    - name: x # is the name of variable
      value: website1 
    ports:
    - containerPort: 80  # application port 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
